### ISSUE TITLE
Instructions for installing?

### ISSUE THREAD

**Issue by xhevahir** [dragly/KeypressCounter#1]
I don't know how to run/install this (or indeed any PHP script). I tried running 'php main.php' from the command line and got this error message: 'PHP Fatal error: Call to undefined function register_activation_hook() in ~/KeypressCounter/server/keyboard-counter/main.php on line 33.' Do I need to change main.php where it says '**FILE**'? Or something else, maybe? Thanks for any pointers.

**Comment by dragly** [comment]
Sorry about the lack of documentation. This was just a test project that was thrown together and abandoned. The server is a WordPress plugin and should be installed by copying the entire directory into wp-content/plugins. I haven't tested this in three years, so I can't guarantee that it still works.
